=== administration-solrep/EPP/socle_transverse-EPP-3.10/socle-transverse-interoperability/src/main/resources/wsdl/dictao/d2s/D2SInterfaceFrontEnd.xsd
<?xml version="1.0" encoding="UTF-8"?>

<s:schema xmlns:s="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" xmlns:tns="http://www.dictao.com/D2S/Interface"
	targetNamespace="http://www.dictao.com/D2S/Interface">


	<s:element name="signatureEx">
		<s:complexType>
			<s:sequence>
				<s:element minOccurs="1" maxOccurs="1" name="requestId"
					type="s:string" />
				<s:element minOccurs="1" maxOccurs="1" name="transactionId"
					type="s:string" />
				<s:element minOccurs="1" maxOccurs="1" name="tag" type="s:string" />
				<s:element minOccurs="1" maxOccurs="1" name="dataToSign"
					type="tns:dataType" />
				<s:element minOccurs="0" maxOccurs="1" name="detachedSignature"
					type="tns:dataType" />
				<s:element minOccurs="1" maxOccurs="1" name="signatureFormat"
					type="s:string" />
				<s:element minOccurs="1" maxOccurs="1" name="signatureType"
					type="s:string" />
				<s:element minOccurs="0" maxOccurs="1" name="signatureParameter"
					type="s:string" />
				<s:element minOccurs="0" maxOccurs="1" name="signatureContext"
					type="tns:contextType" />
				<s:element minOccurs="0" maxOccurs="1" name="pluginParameter"
					type="tns:ArrayOfPluginParameterStruct" />
			</s:sequence>
		</s:complexType>
	</s:element>
	<s:element name="prepareSignatureEx">
		<s:complexType>
			<s:sequence>
				<s:element minOccurs="1" maxOccurs="1" name="requestId"
					type="s:string" />
				<s:element minOccurs="1" maxOccurs="1" name="transactionId"
					type="s:string" />
				<s:element minOccurs="1" maxOccurs="1" name="tag" type="s:string" />
				<s:element minOccurs="1" maxOccurs="1" name="keyContainerFormat"
					type="s:string" />
				<s:element minOccurs="0" maxOccurs="1" name="keyContainerType"
					type="s:string" />
				<s:element minOccurs="0" maxOccurs="1" name="keyContainerParameter"
					type="s:string" />
				<s:element minOccurs="0" maxOccurs="1" name="properties"
					type="tns:dataType" />
				<s:element minOccurs="0" maxOccurs="1" name="pluginParameter"
					type="tns:ArrayOfPluginParameterStruct" />
			</s:sequence>
		</s:complexType>
	</s:element>
	<s:simpleType name="dataEncoding">
		<s:restriction base="s:string">
			<s:enumeration value="gzEnc" />
			<s:enumeration value="b64Enc" />
			<s:enumeration value="gzb64Enc" />
		</s:restriction>
	</s:simpleType>
	<s:complexType name="contextType">
		<s:sequence>
			<s:element minOccurs="0" maxOccurs="1" name="contextId"
				type="s:string" />
			<s:element minOccurs="0" maxOccurs="1" name="certificate"
				type="tns:dataType" />
			<s:element minOccurs="0" maxOccurs="1" name="certificateRequest"
				type="tns:dataType" />
			<s:element minOccurs="0" maxOccurs="1" name="wrappedPrivateKey"
				type="tns:dataType" />
		</s:sequence>
	</s:complexType>
	<s:complexType name="dataType">
		<s:choice>
			<s:element name="value" type="tns:dataString" />
			<s:element name="binaryValue" type="tns:dataBinary" />
		</s:choice>
	</s:complexType>
	<s:complexType name="dataString">
		<s:simpleContent>
			<s:extension base="s:string">
				<s:attribute name="dataFormat" type="tns:dataEncoding"
					use="optional" />
			</s:extension>
		</s:simpleContent>
	</s:complexType>
	<s:complexType name="dataBinary">
		<s:simpleContent>
			<s:extension base="s:base64Binary">
				<s:attribute name="dataFormat" type="tns:dataEncoding"
					use="optional" />
			</s:extension>
		</s:simpleContent>
	</s:complexType>
	<s:complexType name="ArrayOfPluginParameterStruct">
		<s:sequence>
			<s:element minOccurs="0" maxOccurs="unbounded" name="PluginParameterStruct"
				nillable="true" type="tns:PluginParameterStruct" />
		</s:sequence>
	</s:complexType>
	<s:complexType name="PluginParameterStruct">
		<s:sequence>
			<s:element minOccurs="1" maxOccurs="1" name="Label" type="s:string" />
			<s:element minOccurs="1" maxOccurs="1" name="Data" type="s:string" />
		</s:sequence>
	</s:complexType>
	<s:element name="signatureExResponse">
		<s:complexType>
			<s:sequence>
				<s:element minOccurs="0" maxOccurs="1" name="signatureExResult"
					type="tns:D2SResponseEx" />
			</s:sequence>
		</s:complexType>
	</s:element>
	<s:complexType name="D2SResponseEx">
		<s:sequence>
			<s:element minOccurs="1" maxOccurs="1" name="opStatus"
				type="s:int" />
			<s:element minOccurs="1" maxOccurs="1" name="D2SStatus"
				type="s:int" />
			<s:element minOccurs="1" maxOccurs="1" name="requestId"
				type="s:string" />
			<s:element minOccurs="0" maxOccurs="1" name="D2SArchiveId"
				type="s:string" />
			<s:element minOccurs="0" maxOccurs="1" name="D2SSignature"
				type="tns:dataType" />
			<s:element minOccurs="0" maxOccurs="1" name="SignatureContext"
				type="tns:contextType" />
			<s:element minOccurs="0" maxOccurs="1" name="pluginResponse"
				type="tns:ArrayOfPluginResponseStruct" />
		</s:sequence>
	</s:complexType>
	<s:complexType name="D2SArchiveResponseEx">
		<s:sequence>
			<s:element minOccurs="1" maxOccurs="1" name="opStatus"
				type="s:int" />
			<s:element minOccurs="1" maxOccurs="1" name="requestId"
				type="s:string" />
			<s:element minOccurs="0" maxOccurs="1" name="D2SProof"
				type="s:string" />
			<s:element minOccurs="0" maxOccurs="1" name="pluginResponse"
				type="tns:ArrayOfPluginResponseStruct" />
		</s:sequence>
	</s:complexType>
	<s:complexType name="ArrayOfPluginResponseStruct">
		<s:sequence>
			<s:element minOccurs="0" maxOccurs="unbounded" name="PluginResponseStruct"
				nillable="true" type="tns:PluginResponseStruct" />
		</s:sequence>
	</s:complexType>
	<s:complexType name="PluginResponseStruct">
		<s:sequence>
			<s:element minOccurs="1" maxOccurs="1" name="Label" type="s:string" />
			<s:element minOccurs="1" maxOccurs="1" name="Response"
				type="s:string" />
		</s:sequence>
	</s:complexType>
	<s:element name="getArchiveEx">
		<s:complexType>
			<s:sequence>
				<s:element minOccurs="1" maxOccurs="1" name="requestId"
					type="s:string" />
				<s:element minOccurs="1" maxOccurs="1" name="archiveId"
					type="s:string" />
				<s:element minOccurs="0" maxOccurs="1" name="pluginParameter"
					type="tns:ArrayOfPluginParameterStruct" />
			</s:sequence>
		</s:complexType>
	</s:element>
	<s:element name="getArchiveExResponse">
		<s:complexType>
			<s:sequence>
				<s:element minOccurs="0" maxOccurs="1" name="getArchiveExResult"
					type="tns:D2SArchiveResponseEx" />
			</s:sequence>
		</s:complexType>
	</s:element>
	<s:element name="prepareSignatureExResponse">
		<s:complexType>
			<s:sequence>
				<s:element minOccurs="1" maxOccurs="1"
					name="prepareSignatureExResult" type="tns:D2SResponseEx" />
			</s:sequence>
		</s:complexType>
	</s:element>


</s:schema>

=== administration-solrep/EPP/socle_transverse-EPP-3.10/socle-transverse-interoperability/src/main/resources/fr/dila/st/soap/stub/d2s/D2SInterfaceFrontEnd_signatureExResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:signatureExResponse xmlns:tns="http://www.dictao.com/D2S/Interface"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dictao.com/D2S/Interface ../../../../../../wsdl/dictao/d2s/D2SInterfaceFrontEnd.xsd ">


	<tns:signatureExResult>

		<tns:opStatus>0</tns:opStatus>
		<tns:D2SStatus>0</tns:D2SStatus>

		<tns:requestId>REQUEST_ID_D2S_REPONSES_001</tns:requestId>

		<tns:D2SArchiveId>ARCHIVE_UNIQUE_ID_001</tns:D2SArchiveId>

		<tns:D2SSignature>
			<tns:binaryValue>PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyIgeG1sbnM6eGFkPSJodHRwOi8vdXJpLmV0c2kub3JnLzAxOTAzL3YxLjMuMiMiIElkPSJUQU9fMV9TaWduYXR1cmUiPjxkczpTaWduZWRJbmZvIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj48ZHM6Q2Fub25pY2FsaXphdGlvbk1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjcnNhLXNoYTEiLz48ZHM6UmVmZXJlbmNlIFVSST0iI1RBT18xX1NpZ25lZE1hbmlmZXN0IiBUeXBlPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjTWFuaWZlc3QiPjxkczpUcmFuc2Zvcm1zPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48L2RzOlRyYW5zZm9ybXM+PGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNzaGExIi8+PGRzOkRpZ2VzdFZhbHVlPnkycGVqQVdiRHkzYkpqc0RGZDBYUjhweXZVbz08L2RzOkRpZ2VzdFZhbHVlPjwvZHM6UmVmZXJlbmNlPjxkczpSZWZlcmVuY2UgeG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiIFR5cGU9Imh0dHA6Ly91cmkuZXRzaS5vcmcvMDE5MDMjU2lnbmVkUHJvcGVydGllcyIgVVJJPSIjVEFPXzFfU2lnbmVkUHJvcGVydGllcyI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvZHM6VHJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3NoYTEiLz48ZHM6RGlnZXN0VmFsdWU+N1ZsaXdaMzhJV1dTN2s3ZmF4ZU11enNvQ2tzPTwvZHM6RGlnZXN0VmFsdWU+PC9kczpSZWZlcmVuY2U+PC9kczpTaWduZWRJbmZvPjxkczpTaWduYXR1cmVWYWx1ZSBJZD0iVEFPXzFfU2lnbmF0dXJlVmFsdWUiPmhDSnVhbHpqMUpFZVhrS1M4ci9RR1U1WUNNUWNNdU5RQTk0a2F1SWxYTXYxYVJGRk5IQi9qYmhYYmQ3THZYVlQKUW53bHJOWHJ0TVROcGFxdFBCbmJ6RkE4aUJySFIrZE9qSGV0aVUxUU03eUdJLyswdTN1YlM2R25CM0N2NjVmVgpzSCtDbklEMjR3aXJFWGFaYmZPeVdtNUVSQ0VPdG1ILzZ0R0ZwN05BOUFBPTwvZHM6U2lnbmF0dXJlVmFsdWU+PGRzOktleUluZm8+PGRzOlg1MDlEYXRhPjxkczpYNTA5Q2VydGlmaWNhdGU+TUlJRHlqQ0NBcktnQXdJQkFnSUNCQ3d3RFFZSktvWklodmNOQVFFRkJRQXdnWXN4Q3pBSkJnTlZCQVlUQWtaU01STXdFUVlEVlFRSUV3cFRiMjFsTFZOMFlYUmxNUTR3REFZRFZRUUhFd1ZRWVhKcGN6RVNNQkFHQTFVRUNoTUpSR2xqZEdGdklGTkJNUkF3RGdZRFZRUUxFd2RCYm5sVGFXZHVNVEV3THdZRFZRUURFeWhCZFhSdmNtbDBaU0JrWlNCalpYSjBhV1pwWTJGMGFXOXVJRVJwWTNSaGJ5QkJibmxUYVdkdU1CNFhEVEE0TURjeE9ERXhOVEl5TmxvWERURTRNRGN4TmpFeE5USXlObG93WVRFTE1Ba0dBMVVFQmhNQ1JsSXhEREFLQmdOVkJBZ1RBMGxFUmpFT01Bd0dBMVVFQnhNRlVHRnlhWE14RnpBVkJnTlZCQW9URGtSbGJXOGdSR2xqZEdGdklGTkJNUnN3R1FZRFZRUURFeEpFWlcxdklFUXlVeUJRY205dlpsTnBaMjR3Z1o4d0RRWUpLb1pJaHZjTkFRRUJCUUFEZ1kwQU1JR0pBb0dCQUppOHBsM1BvYXJqNTlvZ3oxRWhxMGUyQUVpSWlaK0EwYXZnRXFscisraDc4aHM2bk02QzZiSnRLcXdxanFlV2ZHOEFmeFhoM1E4T1FaR0FsYmxuR3JZQkk4d210NmhFbDdKNUtIY0oyRlhPbXJrbVExdUl3bDJEbHRSMWFUTkp2emlURDQwYng3TCtWNnNpZmxvRFFhblJpVWFnMm1RRHcvTUM5UXFNa251UkFnTUJBQUdqZ2VRd2dlRXdDUVlEVlIwVEJBSXdBREFMQmdOVkhROEVCQU1DQnNBd0VRWUpZSVpJQVliNFFnRUJCQVFEQWdXZ01EZ0dDV0NHU0FHRytFSUJEUVFyRmlsSmJuUmxjbTVoYkNCRWFXTjBZVzhnVUV0SklFZGxibVZ5WVhSbFpDQkRaWEowYVdacFkyRjBaVEE2QmdOVkhSOEVNekF4TUMrZ0xhQXJoaWxvZEhSd09pOHZkM2QzTG1ScFkzUmhieTVqYjIwdlFXNTVVMmxuYmk5QmJubFRhV2R1TG1OeWJEQWRCZ05WSFE0RUZnUVVPOG9UWTYvd2RyTjB0Z0tBYmZvMndZcTMvdkV3SHdZRFZSMGpCQmd3Rm9BVWJrRDdJYklsRSt5UkswU09PeFpsTXFzbkFVZ3dEUVlKS29aSWh2Y05BUUVGQlFBRGdnRUJBTDJBVWx2UXJKNlkwSVAwdE9kUStpYkdjT25XS2x0dFpodGhEcGkxc0xLQUUwMnVHaE85aERrZGhBSndXdlFOOW8rcVp2aUNjMHhjNlIraC9aMEVyTm9hWGJMeHQxaUZCU05va0FJUlR3OHZRenhqWm5WeVQzL1drNDNMcXlPdTF5Wk5KZlRoSDRUbVVDa2hqRmlabjdibldxNlBoQWxZcXd0NWgzZWtFOXZMQ05YUGhOVTVmYnlEU2pWMG1TZ0NnTkU2Mm80TGo2eExOaGtNcjQyeWdWdkpuSFNvSjNvSXJzc09weWJLRTdhUSt0SmRmZ1p0SWY0Mm52QWR0RDNDN2tJc2JOL01Ub3V0SitQM0NiNWVqdDhxaEx0dEZhSzhVZFF2QXR0ZDRPbVR2dU8vS3pMMm9aREFHamt5K1htQ2tydXhFV2dmQkFjRTh1ZVdOOEJNc3BzPTwvZHM6WDUwOUNlcnRpZmljYXRlPjwvZHM6WDUwOURhdGE+PC9kczpLZXlJbmZvPjxkczpPYmplY3Q+PGRzOk1hbmlmZXN0IElkPSJUQU9fMV9TaWduZWRNYW5pZmVzdCI+PGRzOlJlZmVyZW5jZSBVUkk9IiI+PGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZW5jI3NoYTI1NiIvPjxkczpEaWdlc3RWYWx1ZT5PL1VmMmlNaXdXVmN0a3ZRZk5QdlBHWFRpVkZPalh3algrTGNZWTE3bi9BPTwvZHM6RGlnZXN0VmFsdWU+PC9kczpSZWZlcmVuY2U+PC9kczpNYW5pZmVzdD48L2RzOk9iamVjdD48ZHM6T2JqZWN0IHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj48eGFkOlF1YWxpZnlpbmdQcm9wZXJ0aWVzIHhtbG5zOnhhZD0iaHR0cDovL3VyaS5ldHNpLm9yZy8wMTkwMy92MS4zLjIjIiBUYXJnZXQ9IiNUQU9fMV9TaWduYXR1cmUiPjx4YWQ6U2lnbmVkUHJvcGVydGllcyBJZD0iVEFPXzFfU2lnbmVkUHJvcGVydGllcyI+PHhhZDpTaWduZWRTaWduYXR1cmVQcm9wZXJ0aWVzPjx4YWQ6U2lnbmluZ1RpbWU+MjAxMS0wOC0wNFQxMzo0NTo1OFo8L3hhZDpTaWduaW5nVGltZT48eGFkOlNpZ25pbmdDZXJ0aWZpY2F0ZT48eGFkOkNlcnQ+PHhhZDpDZXJ0RGlnZXN0PjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPjxkczpEaWdlc3RWYWx1ZT5GOGtBazk3VjdieEFGSHROQWlyanBWeTVoTHM9PC9kczpEaWdlc3RWYWx1ZT48L3hhZDpDZXJ0RGlnZXN0Pjx4YWQ6SXNzdWVyU2VyaWFsPjxkczpYNTA5SXNzdWVyTmFtZT5DTj1BdXRvcml0ZSBkZSBjZXJ0aWZpY2F0aW9uIERpY3RhbyBBbnlTaWduLE9VPUFueVNpZ24sTz1EaWN0YW8gU0EsTD1QYXJpcyxTVD1Tb21lLVN0YXRlLEM9RlI8L2RzOlg1MDlJc3N1ZXJOYW1lPjxkczpYNTA5U2VyaWFsTnVtYmVyPjEwNjg8L2RzOlg1MDlTZXJpYWxOdW1iZXI+PC94YWQ6SXNzdWVyU2VyaWFsPjwveGFkOkNlcnQ+PC94YWQ6U2lnbmluZ0NlcnRpZmljYXRlPjwveGFkOlNpZ25lZFNpZ25hdHVyZVByb3BlcnRpZXM+PC94YWQ6U2lnbmVkUHJvcGVydGllcz48L3hhZDpRdWFsaWZ5aW5nUHJvcGVydGllcz48L2RzOk9iamVjdD48L2RzOlNpZ25hdHVyZT4K</tns:binaryValue>
		</tns:D2SSignature>

	</tns:signatureExResult>


</tns:signatureExResponse>
